# Generated by Django 4.0.5 on 2023-01-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_post_alter_question_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creation_date']},
        ),
    ]
