# Generated by Django 4.0.5 on 2023-01-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
