# Generated by Django 4.0.5 on 2023-02-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
